# Site wide configuration

title:            ReputationVIP R&D
locale:           en_US
url:              #http://reputationvip.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: ReputationVIP
  avatar: avatars/reputationvip.png
  bio: "Bonjour et bienvenue sur le blog de l’équipe R&D de Reputation VIP.<br/>
		Vous trouverez ici des articles techniques, des exemples de code, des présentations pour débuter ou se perfectionner sur des technos et des méthodologies actuelles. Nous vous ferons part aussi de nos ressentis sur notre manière de nous organiser pour travailler le mieux possible ensemble.
		N’hésitez pas à nous faire part de vos commentaires."
  email: #email
  web: http://www.reputationvip.com
  disqus-shortname: 
  twitter: reputationvip
  facebook: reputationvip
  google:
    plus: reputationvip
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: ReputationVIP
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: reputation-vip
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
